# Generated by Django 3.0 on 2019-12-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191206_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='media/article_img/', verbose_name='文章图片'),
        ),
    ]
